//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Menu
{
	private Storage storage;
        private Autorization auth;
        private Search search;
        private Return returnProduct;
        private Supply supply;
        private Sell sell;

        public Menu(Storage storage, Autorization auth, Search search, Return returnProduct, Supply supply, Sell sell)
        {
            this.storage = storage;
            this.auth = auth;
            this.search = search;
            this.returnProduct = returnProduct;
            this.supply = supply;
            this.sell = sell;
        }

        public void ShowMenu()
        {
            while (true)
            {
                Console.WriteLine("\n=== MENU ===");
                Console.WriteLine("1. Sale of goods");
                Console.WriteLine("2. Acceptance of deliveries");
                Console.WriteLine("3. Return of goods");
                Console.WriteLine("4. Check availability");
                Console.WriteLine("5. Add a new cashier");
                Console.WriteLine("6. Show warehouse");
                Console.WriteLine("0. Exit");
                Console.Write("Select an action: ");

                string choice = Console.ReadLine();

                switch (choice)
                {
                    case "1":
                        SellProduct();
                        break;
                    case "2":
                        GetSupply();
                        break;
                    case "3":
                        ReturnProduct();
                        break;
                    case "4":
                        CheckAvailability();
                        break;
                    case "5":
                        AddNewCashier();
                        break;
                    case "6":
                        ShowStock();
                        break;
                    case "0":
                        Console.WriteLine("Completion of work...");
                        return;
                    default:
                        Console.WriteLine("Wrong choice");
                        break;
                }
            }
        }

        private void SellProduct()
        {
            Console.Write("Entering the product article number: ");
            int article = int.Parse(Console.ReadLine());

            Console.Write("Entering the quantity of goods: ");
            int quantity = int.Parse(Console.ReadLine());

            sell.SellF(article, quantity, storage.ReadStock());
        }

        private void GetSupply()
        {
            Console.Write("Entering the product article number: ");
            int article = int.Parse(Console.ReadLine());

            Console.Write("Entering the quantity of goods: ");
            int quantity = int.Parse(Console.ReadLine());

            supply.GetSupply(article, quantity, storage.ReadStock());
        }

        private void ReturnProduct()
        {
            Console.Write("Entering the product article number: ");
            int article = int.Parse(Console.ReadLine());

            Console.Write("Entering the quantity of goods: ");
            int quantity = int.Parse(Console.ReadLine());

            returnProduct.Ret(article, quantity, storage.ReadStock());
            Console.WriteLine("Return completed");
        }

        private void CheckAvailability()
        {
            Console.Write("Entering the product article number: ");
            int article = int.Parse(Console.ReadLine());

            var product = search.SearchF(article, storage.ReadStock());
            if (product != null)
            {
                Console.WriteLine("Product: article number ", product.Article, "quantity: ", product.Quantity);
            }
            else
            {
                Console.WriteLine("Product not found");
            }
        }

        private void AddNewCashier()
        {
            Console.Write("Enter the new cashier's login: ");
            string login = Console.ReadLine();
            auth.NewCashier(login);
        }

        private void ShowStock()
        {
            var stock = storage.ReadStock();
            Console.WriteLine("\n=== WAREHOUSE ===");
            foreach (var product in stock)
            {
                Console.WriteLine("Article: ", product.Article, ", Quantity: ", product.Quantity);
            }
        }
}

