//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("=== CASH REGISTER PROGRAM ===");
        Console.Write("Login: ");
        string login = Console.ReadLine();
        Console.Write("Password: ");
        string password = Console.ReadLine();

        Storage storage = new Storage();
        Autorization auth = new Autorization();
        Search search = new Search();
        Return returnProduct = new Return();
        Supply supply = new Supply();
        Sell sell = new Sell();

        if (auth.Authorization(login, password))
        {
            Console.WriteLine("Authorization successful!");
            Menu menu = new Menu(storage, auth, search, returnProduct, supply, sell);
            menu.ShowMenu();
        }
        else
        {
                Console.WriteLine("Authorization error!");
                Console.ReadLine();
        }
    }
}

