//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Storage
{
    public List<Product> products = new List<Product>();
    public void Correct(string Type, long Article, int Value)
	{
        var product = products.FirstOrDefault(p => p.Article == Article);
        if (Type == "quantity" && product != null)
        {
            product.Quantity = Value;
        }
	}

	public List<Product> ReadStock()
	{
        return products.ToList();
	}

	public void WriteStock(List<Product> Pr)
	{
        products = Pr.ToList();
	}

}

