//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Autorization
{
    private List<Cashier> cashiers = new List<Cashier>();
	public Autorization()
	{
        cashiers.Add(new Cashier { Login = "admin", Password = "1234" });
	}

    public bool Authorization(string login, string password)
    {
        return cashiers.Any(c => c.Login == login && c.Password == password);
    }

	public void NewCashier(string login)
	{
		 var newCashier = new Cashier { Login = login };
            newCashier.Password = newCashier.GenerateNewPassword();
            cashiers.Add(newCashier);
            Console.WriteLine("A new cashier has been created. Login: ", login, "Password: ", newCashier.Password);
	}

	public List<Cashier> ReadCashier()
	{
        return cashiers.ToList();
	}

	public void WriteCashier(List<Cashier> Pr)
	{
        cashiers = Pr.ToList();
	}

}

