//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Search
{
    public Product SearchF(int article, List<Product> stock)
    {
        return stock.FirstOrDefault(p => p.Article == article);
    }

}

