//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Sell
{
    public bool SellF(int article, int quantity, List<Product> stock)
	{
        var product = stock.FirstOrDefault(p => p.Article == article);
        if (product != null && product.Quantity >= quantity)
        {
            product.Quantity -= quantity;
            Console.WriteLine("Sold: article ", article, " quantity", quantity);
            return true;
        }
        Console.WriteLine("Error: Product ", article, "is missing or insufficient");
        return false;
	}

}

