//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Supply
{
	public void GetSupply(long article, int quantity, List<Product> stock)
    {
        var product = stock.FirstOrDefault(p => p.Article == article);
        if (product != null)
        {
            product.Quantity += quantity;
        }
        else
        {
            stock.Add(new Product { Article = article, Quantity = quantity });
        }
        Console.WriteLine("Supply: article ", article, "quantity", quantity);
    }
}

